#name of the workflow
name: push-test
#what events trigger this workflow
on: [push, pull_request]

#jobs run in parallel
jobs: 
  #jobID
  docker-push:
    # Name of the job on github
    name: Build and Push Docker
    # docker image the runner is using
    runs-on: [ubuntu-latest]
    
    # steps of the job run sequentially  
    steps: 
      - name: checkout
        uses: actions/checkout@v2
        
      - name: List
        run: ls -al
        
        #https://github.com/marketplace/actions/docker-publish
        #https://www.docker.com/blog/first-docker-github-action-is-here/
      - name: Dockerize
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bardelch/workflow-tests
          tags: latest
